apiVersion: v1
kind: Pod
metadata:
  name: web
#  labels:
#    key: value
spec:
  volumes:
    - name: app
      emptyDir: {}

  containers:
    - name: nginx
      image: docker.io/ujhgj/kubernetes-intro-web:0.0.1
      volumeMounts:
        - name: app
          mountPath: /app

  initContainers:
    - name: init-nginx
      image: busybox
      volumeMounts:
        - name: app
          mountPath: /app
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']


